language: php

php:
  - 7.2
  - 7.3
  - 7.4

sudo: false

services:
  - mysql

install:
  - mysql -e 'CREATE DATABASE travis_test;'
  - composer install

script:
  - php vendor/bin/codecept run unit --coverage-xml --env travis

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
